### ISSUE TITLE
login/register system broken!

### ISSUE THREAD

**Issue by SoaringRadio** [Sniddl/SM#23]
beta.sniddl.com user system broken. can't login with right credentials?

**Comment by Sam-Ainsworth** [comment]
I've fixed the login system my end.  Also upgraded from mysqli to pdo. Encryption has also been upgraded. I'll do the register tomorrow.

**Comment by SoaringRadio** [comment]
sounds good. When you are done make sure to move the issue to done, on waffle.io

**Comment by Sam-Ainsworth** [comment]
Yeah, Its not completed just yet anyway. When I get home Ill finish it off.
